services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend-dev
    ports:
      - "${APP_PORT_DEV}:8080"
    depends_on:
      - postgres-dev
      - minio-setup-dev
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-dev:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      JAVA_TOOL_OPTIONS: -Duser.timezone=America/Sao_Paulo
      TZ: America/Sao_Paulo
      MINIO_URL: http://minio-dev:9000
      MINIO_ACCESS_KEY: ${MINIO_ROOT_USER}
      MINIO_SECRET_KEY: ${MINIO_ROOT_PASSWORD}
      MINIO_BUCKET_NAME: ${MINIO_BUCKET_NAME}
      CORS_ALLOWED_ORIGIN: ${CORS_ALLOWED_ORIGIN}
      SPRING_PROFILES_ACTIVE: dev
    networks:
      - dcriar-net

networks:
  dcriar-net:
    external: false
