-- RESPONSABILIDADE ÚNICA: Criar a estrutura de tabelas inicial do projeto.

-- Tabela para o "catálogo" de matérias-primas
CREATE TABLE tipos_materia_prima (
                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     nome VARCHAR(150) NOT NULL UNIQUE,
                                     unidade_de_consumo VARCHAR(50) NOT NULL
);

-- Tabela para os lotes físicos de matéria-prima no estoque
CREATE TABLE lotes_materia_prima (
                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     tipo_materia_prima_id BIGINT NOT NULL,
                                     unidade_de_estoque VARCHAR(50) NOT NULL,
                                     atributos JSONB,
                                     lote_de_origem_id BIGINT,
                                     CONSTRAINT fk_lote_tipo_materia_prima FOREIGN KEY (tipo_materia_prima_id) REFERENCES tipos_materia_prima(id),
                                     CONSTRAINT fk_lote_origem FOREIGN KEY (lote_de_origem_id) REFERENCES lotes_materia_prima(id)
);

-- Tabela de "Livro-Razão" para todas as movimentações de estoque de INSUMOS
CREATE TABLE movimentacoes_estoque_lote (
                                            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                            lote_id BIGINT NOT NULL,
                                            data TIMESTAMP WITH TIME ZONE NOT NULL,
                                            tipo VARCHAR(50) NOT NULL,
                                            quantidade NUMERIC(19, 4) NOT NULL,
                                            motivo VARCHAR(255),
                                            CONSTRAINT fk_mov_lote FOREIGN KEY (lote_id) REFERENCES lotes_materia_prima(id) ON DELETE CASCADE
);

-- Tabela de canais de venda
CREATE TABLE canais_venda (
                              id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                              nome VARCHAR(50) NOT NULL UNIQUE
);

-- Tabela de produtos acabados
CREATE TABLE produtos (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          nome VARCHAR(150) NOT NULL UNIQUE,
                          sku VARCHAR(50) NOT NULL UNIQUE,
                          descricao TEXT,
                          cor VARCHAR(50) NOT NULL,
                          unidades_por_produto INT NOT NULL,
                          ativo BOOLEAN NOT NULL DEFAULT TRUE,
                          foto_principal_url VARCHAR(255)
);

-- Tabela para a "receita" de cada produto (versão inicial)
CREATE TABLE composicao_produto (
                                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                    produto_id BIGINT NOT NULL,
                                    tipo_materia_prima_id BIGINT NOT NULL,
                                    gasto_material_por_unidade NUMERIC(19, 4) NOT NULL,
                                    CONSTRAINT fk_composicao_produto FOREIGN KEY (produto_id) REFERENCES produtos(id) ON DELETE CASCADE,
                                    CONSTRAINT fk_composicao_tipo_materia_prima FOREIGN KEY (tipo_materia_prima_id) REFERENCES tipos_materia_prima(id)
);

-- Tabela para os diferentes preços de um produto
CREATE TABLE precos (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        produto_id BIGINT NOT NULL,
                        tipo_preco VARCHAR(50) NOT NULL,
                        valor NUMERIC(19, 2) NOT NULL,
                        valor_promocional NUMERIC(19, 2),
                        promocao_ativa BOOLEAN NOT NULL DEFAULT FALSE,
                        CONSTRAINT fk_preco_produto FOREIGN KEY (produto_id) REFERENCES produtos(id) ON DELETE CASCADE
);

-- Tabela para o estoque de produtos acabados por canal (Estoque Distribuído)
CREATE TABLE estoques (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          produto_id BIGINT NOT NULL,
                          canal_venda_id BIGINT NOT NULL,
                          quantidade INT NOT NULL,
                          CONSTRAINT fk_estoque_produto FOREIGN KEY (produto_id) REFERENCES produtos(id) ON DELETE CASCADE,
                          CONSTRAINT fk_estoque_canal FOREIGN KEY (canal_venda_id) REFERENCES canais_venda(id)
);

