-- RESPONSABILIDADE: Evoluir o schema, adicionando a tabela para o "Livro-Razão" de produtos acabados.

CREATE TABLE movimentacoes_estoque_produto (
                                               id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                               produto_id BIGINT NOT NULL,
                                               data TIMESTAMP WITH TIME ZONE NOT NULL,
                                               tipo VARCHAR(50) NOT NULL,
                                               quantidade INT NOT NULL,
                                               motivo VARCHAR(255),
                                               CONSTRAINT fk_mov_produto FOREIGN KEY (produto_id) REFERENCES produtos(id) ON DELETE CASCADE
);