-- RESPONSABILIDADE: Evoluir o schema, adicionando as tabelas para o Módulo de Vendas.

CREATE TABLE vendas (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       data_venda TIMESTAMP WITH TIME ZONE NOT NULL,
                       canal_venda_id BIGINT NOT NULL,
                       valor_total NUMERIC(19, 2) NOT NULL,
                       CONSTRAINT fk_venda_canal_venda FOREIGN KEY (canal_venda_id) REFERENCES canais_venda(id)
);

CREATE TABLE itens_venda (
                            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            venda_id BIGINT NOT NULL,
                            produto_id BIGINT NOT NULL,
                            quantidade INT NOT NULL,
                            preco_unitario NUMERIC(19, 2) NOT NULL,
                            preco_total NUMERIC(19, 2) NOT NULL,
                            CONSTRAINT fk_item_venda_venda FOREIGN KEY (venda_id) REFERENCES vendas(id) ON DELETE CASCADE,
                            CONSTRAINT fk_item_venda_produto FOREIGN KEY (produto_id) REFERENCES produtos(id)
);