-- RESPONSABILIDADE: Unificar as migrações do modelo de produção híbrida (V4 a V8).

-- Originado da V4: Adiciona a coluna de custo à tabela de movimentações de lote.
ALTER TABLE movimentacoes_estoque_lote
    ADD COLUMN custo_por_unidade_base NUMERIC(19, 8);

-- Originado da V5: Remove a antiga estrutura de "receita".
DROP TABLE IF EXISTS composicao_produto;

-- Originado da V5: Aprimora a tabela de produtos para ser o "molde".
ALTER TABLE produtos
    ADD COLUMN tipo_materia_prima_id BIGINT,
    ADD COLUMN largura_cm NUMERIC(10, 2),
    ADD COLUMN comprimento_cm NUMERIC(10, 2);

-- Adiciona a chave estrangeira para ligar o produto ao seu material principal.
ALTER TABLE produtos
    ADD CONSTRAINT fk_produto_tipo_materia_prima
        FOREIGN KEY (tipo_materia_prima_id) REFERENCES tipos_materia_prima(id);

-- Tabela consolidada a partir de V5, V6, e V8: Cria a tabela de ordens de corte com todas as colunas.
CREATE TABLE ordens_de_corte (
                                 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                 produto_id BIGINT NOT NULL,
                                 lote_principal_id BIGINT NOT NULL,
                                 quantidade_produzida INT NOT NULL,
                                 modo_calculo VARCHAR(50) NOT NULL,
    -- Dimensões Finais (seja calculado ou manual)
                                 largura_final_cm NUMERIC(10, 2) NOT NULL,
                                 comprimento_final_cm NUMERIC(10, 2) NOT NULL,
    -- Campos de auditoria
                                 data_criacao TIMESTAMP WITH TIME ZONE NOT NULL,
                                 motivo VARCHAR(255),
    -- Coluna da V6
                                 canal_venda_destino_id BIGINT,
    -- Colunas da V8
                                 margem_superior_cm DECIMAL(10, 2),
                                 margem_inferior_cm DECIMAL(10, 2),
                                 margem_esquerda_cm DECIMAL(10, 2),
                                 margem_direita_cm DECIMAL(10, 2),

                                 CONSTRAINT fk_ordem_produto FOREIGN KEY (produto_id) REFERENCES produtos(id),
                                 CONSTRAINT fk_ordem_lote FOREIGN KEY (lote_principal_id) REFERENCES lotes_materia_prima(id)
);

-- Originado da V7: Cria a tabela para os cortes realizados.
CREATE TABLE cortes_realizados (
                                   id BIGSERIAL PRIMARY KEY,
                                   ordem_de_corte_id BIGINT NOT NULL,
                                   largura_cm DECIMAL(10, 2) NOT NULL,
                                   comprimento_cm DECIMAL(10, 2) NOT NULL,
                                   quantidade INT NOT NULL,
                                   tipo VARCHAR(20) NOT NULL,
                                   CONSTRAINT fk_ordem_de_corte FOREIGN KEY (ordem_de_corte_id) REFERENCES ordens_de_corte(id)
);